baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Alfaj0r.com"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["https://images.pexels.com/photos/1054506/pexels-photo-1054506.jpeg"]